package com.coen424.datamodels.services;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

public final class Response {
  private Response() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MetricOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Metric)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>double metric = 2;</code>
     * @return The metric.
     */
    double getMetric();
  }
  /**
   * Protobuf type {@code Metric}
   */
  public static final class Metric extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Metric)
      MetricOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Metric.newBuilder() to construct.
    private Metric(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Metric() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Metric();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Metric(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 17: {

              metric_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Response.internal_static_Metric_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Response.internal_static_Metric_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Metric.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }

    public static final int METRIC_FIELD_NUMBER = 2;
    private double metric_;
    /**
     * <code>double metric = 2;</code>
     * @return The metric.
     */
    @Override
    public double getMetric() {
      return metric_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (metric_ != 0D) {
        output.writeDouble(2, metric_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (metric_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, metric_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Metric)) {
        return super.equals(obj);
      }
      Metric other = (Metric) obj;

      if (getId()
          != other.getId()) return false;
      if (Double.doubleToLongBits(getMetric())
          != Double.doubleToLongBits(
              other.getMetric())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + METRIC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getMetric()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Metric parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Metric parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Metric parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Metric parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Metric parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Metric parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Metric parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Metric parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Metric parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Metric parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Metric parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Metric parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Metric prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Metric}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Metric)
        MetricOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Response.internal_static_Metric_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Response.internal_static_Metric_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Metric.class, Builder.class);
      }

      // Construct using Response.Metric.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        metric_ = 0D;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Response.internal_static_Metric_descriptor;
      }

      @Override
      public Metric getDefaultInstanceForType() {
        return Metric.getDefaultInstance();
      }

      @Override
      public Metric build() {
        Metric result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Metric buildPartial() {
        Metric result = new Metric(this);
        result.id_ = id_;
        result.metric_ = metric_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Metric) {
          return mergeFrom((Metric)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Metric other) {
        if (other == Metric.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getMetric() != 0D) {
          setMetric(other.getMetric());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Metric parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Metric) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private double metric_ ;
      /**
       * <code>double metric = 2;</code>
       * @return The metric.
       */
      @Override
      public double getMetric() {
        return metric_;
      }
      /**
       * <code>double metric = 2;</code>
       * @param value The metric to set.
       * @return This builder for chaining.
       */
      public Builder setMetric(double value) {
        
        metric_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double metric = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMetric() {
        
        metric_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Metric)
    }

    // @@protoc_insertion_point(class_scope:Metric)
    private static final Metric DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Metric();
    }

    public static Metric getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Metric>
        PARSER = new com.google.protobuf.AbstractParser<Metric>() {
      @Override
      public Metric parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Metric(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Metric> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Metric> getParserForType() {
      return PARSER;
    }

    @Override
    public Metric getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BatchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Batch)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Metric metrics = 1;</code>
     */
    java.util.List<Metric>
        getMetricsList();
    /**
     * <code>repeated .Metric metrics = 1;</code>
     */
    Metric getMetrics(int index);
    /**
     * <code>repeated .Metric metrics = 1;</code>
     */
    int getMetricsCount();
    /**
     * <code>repeated .Metric metrics = 1;</code>
     */
    java.util.List<? extends MetricOrBuilder>
        getMetricsOrBuilderList();
    /**
     * <code>repeated .Metric metrics = 1;</code>
     */
    MetricOrBuilder getMetricsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Batch}
   */
  public static final class Batch extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Batch)
      BatchOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Batch.newBuilder() to construct.
    private Batch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Batch() {
      metrics_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Batch();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Batch(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                metrics_ = new java.util.ArrayList<Metric>();
                mutable_bitField0_ |= 0x00000001;
              }
              metrics_.add(
                  input.readMessage(Metric.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          metrics_ = java.util.Collections.unmodifiableList(metrics_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Response.internal_static_Batch_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Response.internal_static_Batch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Batch.class, Builder.class);
    }

    public static final int METRICS_FIELD_NUMBER = 1;
    private java.util.List<Metric> metrics_;
    /**
     * <code>repeated .Metric metrics = 1;</code>
     */
    @Override
    public java.util.List<Metric> getMetricsList() {
      return metrics_;
    }
    /**
     * <code>repeated .Metric metrics = 1;</code>
     */
    @Override
    public java.util.List<? extends MetricOrBuilder>
        getMetricsOrBuilderList() {
      return metrics_;
    }
    /**
     * <code>repeated .Metric metrics = 1;</code>
     */
    @Override
    public int getMetricsCount() {
      return metrics_.size();
    }
    /**
     * <code>repeated .Metric metrics = 1;</code>
     */
    @Override
    public Metric getMetrics(int index) {
      return metrics_.get(index);
    }
    /**
     * <code>repeated .Metric metrics = 1;</code>
     */
    @Override
    public MetricOrBuilder getMetricsOrBuilder(
        int index) {
      return metrics_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < metrics_.size(); i++) {
        output.writeMessage(1, metrics_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < metrics_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, metrics_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Batch)) {
        return super.equals(obj);
      }
      Batch other = (Batch) obj;

      if (!getMetricsList()
          .equals(other.getMetricsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMetricsCount() > 0) {
        hash = (37 * hash) + METRICS_FIELD_NUMBER;
        hash = (53 * hash) + getMetricsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Batch parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Batch parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Batch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Batch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Batch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Batch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Batch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Batch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Batch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Batch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Batch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Batch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Batch prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Batch}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Batch)
        BatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Response.internal_static_Batch_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Response.internal_static_Batch_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Batch.class, Builder.class);
      }

      // Construct using Response.Batch.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMetricsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (metricsBuilder_ == null) {
          metrics_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          metricsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Response.internal_static_Batch_descriptor;
      }

      @Override
      public Batch getDefaultInstanceForType() {
        return Batch.getDefaultInstance();
      }

      @Override
      public Batch build() {
        Batch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Batch buildPartial() {
        Batch result = new Batch(this);
        int from_bitField0_ = bitField0_;
        if (metricsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            metrics_ = java.util.Collections.unmodifiableList(metrics_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.metrics_ = metrics_;
        } else {
          result.metrics_ = metricsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Batch) {
          return mergeFrom((Batch)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Batch other) {
        if (other == Batch.getDefaultInstance()) return this;
        if (metricsBuilder_ == null) {
          if (!other.metrics_.isEmpty()) {
            if (metrics_.isEmpty()) {
              metrics_ = other.metrics_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMetricsIsMutable();
              metrics_.addAll(other.metrics_);
            }
            onChanged();
          }
        } else {
          if (!other.metrics_.isEmpty()) {
            if (metricsBuilder_.isEmpty()) {
              metricsBuilder_.dispose();
              metricsBuilder_ = null;
              metrics_ = other.metrics_;
              bitField0_ = (bitField0_ & ~0x00000001);
              metricsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMetricsFieldBuilder() : null;
            } else {
              metricsBuilder_.addAllMessages(other.metrics_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Batch parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Batch) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Metric> metrics_ =
        java.util.Collections.emptyList();
      private void ensureMetricsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          metrics_ = new java.util.ArrayList<Metric>(metrics_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Metric, Metric.Builder, MetricOrBuilder> metricsBuilder_;

      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public java.util.List<Metric> getMetricsList() {
        if (metricsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(metrics_);
        } else {
          return metricsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public int getMetricsCount() {
        if (metricsBuilder_ == null) {
          return metrics_.size();
        } else {
          return metricsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public Metric getMetrics(int index) {
        if (metricsBuilder_ == null) {
          return metrics_.get(index);
        } else {
          return metricsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public Builder setMetrics(
          int index, Metric value) {
        if (metricsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricsIsMutable();
          metrics_.set(index, value);
          onChanged();
        } else {
          metricsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public Builder setMetrics(
          int index, Metric.Builder builderForValue) {
        if (metricsBuilder_ == null) {
          ensureMetricsIsMutable();
          metrics_.set(index, builderForValue.build());
          onChanged();
        } else {
          metricsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public Builder addMetrics(Metric value) {
        if (metricsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricsIsMutable();
          metrics_.add(value);
          onChanged();
        } else {
          metricsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public Builder addMetrics(
          int index, Metric value) {
        if (metricsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMetricsIsMutable();
          metrics_.add(index, value);
          onChanged();
        } else {
          metricsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public Builder addMetrics(
          Metric.Builder builderForValue) {
        if (metricsBuilder_ == null) {
          ensureMetricsIsMutable();
          metrics_.add(builderForValue.build());
          onChanged();
        } else {
          metricsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public Builder addMetrics(
          int index, Metric.Builder builderForValue) {
        if (metricsBuilder_ == null) {
          ensureMetricsIsMutable();
          metrics_.add(index, builderForValue.build());
          onChanged();
        } else {
          metricsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public Builder addAllMetrics(
          Iterable<? extends Metric> values) {
        if (metricsBuilder_ == null) {
          ensureMetricsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, metrics_);
          onChanged();
        } else {
          metricsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public Builder clearMetrics() {
        if (metricsBuilder_ == null) {
          metrics_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          metricsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public Builder removeMetrics(int index) {
        if (metricsBuilder_ == null) {
          ensureMetricsIsMutable();
          metrics_.remove(index);
          onChanged();
        } else {
          metricsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public Metric.Builder getMetricsBuilder(
          int index) {
        return getMetricsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public MetricOrBuilder getMetricsOrBuilder(
          int index) {
        if (metricsBuilder_ == null) {
          return metrics_.get(index);  } else {
          return metricsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public java.util.List<? extends MetricOrBuilder>
           getMetricsOrBuilderList() {
        if (metricsBuilder_ != null) {
          return metricsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(metrics_);
        }
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public Metric.Builder addMetricsBuilder() {
        return getMetricsFieldBuilder().addBuilder(
            Metric.getDefaultInstance());
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public Metric.Builder addMetricsBuilder(
          int index) {
        return getMetricsFieldBuilder().addBuilder(
            index, Metric.getDefaultInstance());
      }
      /**
       * <code>repeated .Metric metrics = 1;</code>
       */
      public java.util.List<Metric.Builder>
           getMetricsBuilderList() {
        return getMetricsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Metric, Metric.Builder, MetricOrBuilder>
          getMetricsFieldBuilder() {
        if (metricsBuilder_ == null) {
          metricsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Metric, Metric.Builder, MetricOrBuilder>(
                  metrics_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          metrics_ = null;
        }
        return metricsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Batch)
    }

    // @@protoc_insertion_point(class_scope:Batch)
    private static final Batch DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Batch();
    }

    public static Batch getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Batch>
        PARSER = new com.google.protobuf.AbstractParser<Batch>() {
      @Override
      public Batch parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Batch(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Batch> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Batch> getParserForType() {
      return PARSER;
    }

    @Override
    public Batch getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BatchesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Batches)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 rfwid = 1;</code>
     * @return The rfwid.
     */
    int getRfwid();

    /**
     * <code>int32 lastID = 2;</code>
     * @return The lastID.
     */
    int getLastID();

    /**
     * <code>repeated .Batch batches = 3;</code>
     */
    java.util.List<Batch>
        getBatchesList();
    /**
     * <code>repeated .Batch batches = 3;</code>
     */
    Batch getBatches(int index);
    /**
     * <code>repeated .Batch batches = 3;</code>
     */
    int getBatchesCount();
    /**
     * <code>repeated .Batch batches = 3;</code>
     */
    java.util.List<? extends BatchOrBuilder>
        getBatchesOrBuilderList();
    /**
     * <code>repeated .Batch batches = 3;</code>
     */
    BatchOrBuilder getBatchesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Batches}
   */
  public static final class Batches extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Batches)
      BatchesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Batches.newBuilder() to construct.
    private Batches(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Batches() {
      batches_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Batches();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Batches(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              rfwid_ = input.readInt32();
              break;
            }
            case 16: {

              lastID_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                batches_ = new java.util.ArrayList<Batch>();
                mutable_bitField0_ |= 0x00000001;
              }
              batches_.add(
                  input.readMessage(Batch.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          batches_ = java.util.Collections.unmodifiableList(batches_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Response.internal_static_Batches_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Response.internal_static_Batches_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Batches.class, Builder.class);
    }

    public static final int RFWID_FIELD_NUMBER = 1;
    private int rfwid_;
    /**
     * <code>int32 rfwid = 1;</code>
     * @return The rfwid.
     */
    @Override
    public int getRfwid() {
      return rfwid_;
    }

    public static final int LASTID_FIELD_NUMBER = 2;
    private int lastID_;
    /**
     * <code>int32 lastID = 2;</code>
     * @return The lastID.
     */
    @Override
    public int getLastID() {
      return lastID_;
    }

    public static final int BATCHES_FIELD_NUMBER = 3;
    private java.util.List<Batch> batches_;
    /**
     * <code>repeated .Batch batches = 3;</code>
     */
    @Override
    public java.util.List<Batch> getBatchesList() {
      return batches_;
    }
    /**
     * <code>repeated .Batch batches = 3;</code>
     */
    @Override
    public java.util.List<? extends BatchOrBuilder>
        getBatchesOrBuilderList() {
      return batches_;
    }
    /**
     * <code>repeated .Batch batches = 3;</code>
     */
    @Override
    public int getBatchesCount() {
      return batches_.size();
    }
    /**
     * <code>repeated .Batch batches = 3;</code>
     */
    @Override
    public Batch getBatches(int index) {
      return batches_.get(index);
    }
    /**
     * <code>repeated .Batch batches = 3;</code>
     */
    @Override
    public BatchOrBuilder getBatchesOrBuilder(
        int index) {
      return batches_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rfwid_ != 0) {
        output.writeInt32(1, rfwid_);
      }
      if (lastID_ != 0) {
        output.writeInt32(2, lastID_);
      }
      for (int i = 0; i < batches_.size(); i++) {
        output.writeMessage(3, batches_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rfwid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rfwid_);
      }
      if (lastID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lastID_);
      }
      for (int i = 0; i < batches_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, batches_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Batches)) {
        return super.equals(obj);
      }
      Batches other = (Batches) obj;

      if (getRfwid()
          != other.getRfwid()) return false;
      if (getLastID()
          != other.getLastID()) return false;
      if (!getBatchesList()
          .equals(other.getBatchesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RFWID_FIELD_NUMBER;
      hash = (53 * hash) + getRfwid();
      hash = (37 * hash) + LASTID_FIELD_NUMBER;
      hash = (53 * hash) + getLastID();
      if (getBatchesCount() > 0) {
        hash = (37 * hash) + BATCHES_FIELD_NUMBER;
        hash = (53 * hash) + getBatchesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Batches parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Batches parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Batches parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Batches parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Batches parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Batches parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Batches parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Batches parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Batches parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Batches parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Batches parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Batches parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Batches prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Batches}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Batches)
        BatchesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Response.internal_static_Batches_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Response.internal_static_Batches_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Batches.class, Builder.class);
      }

      // Construct using Response.Batches.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBatchesFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        rfwid_ = 0;

        lastID_ = 0;

        if (batchesBuilder_ == null) {
          batches_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          batchesBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Response.internal_static_Batches_descriptor;
      }

      @Override
      public Batches getDefaultInstanceForType() {
        return Batches.getDefaultInstance();
      }

      @Override
      public Batches build() {
        Batches result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Batches buildPartial() {
        Batches result = new Batches(this);
        int from_bitField0_ = bitField0_;
        result.rfwid_ = rfwid_;
        result.lastID_ = lastID_;
        if (batchesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            batches_ = java.util.Collections.unmodifiableList(batches_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.batches_ = batches_;
        } else {
          result.batches_ = batchesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Batches) {
          return mergeFrom((Batches)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Batches other) {
        if (other == Batches.getDefaultInstance()) return this;
        if (other.getRfwid() != 0) {
          setRfwid(other.getRfwid());
        }
        if (other.getLastID() != 0) {
          setLastID(other.getLastID());
        }
        if (batchesBuilder_ == null) {
          if (!other.batches_.isEmpty()) {
            if (batches_.isEmpty()) {
              batches_ = other.batches_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBatchesIsMutable();
              batches_.addAll(other.batches_);
            }
            onChanged();
          }
        } else {
          if (!other.batches_.isEmpty()) {
            if (batchesBuilder_.isEmpty()) {
              batchesBuilder_.dispose();
              batchesBuilder_ = null;
              batches_ = other.batches_;
              bitField0_ = (bitField0_ & ~0x00000001);
              batchesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBatchesFieldBuilder() : null;
            } else {
              batchesBuilder_.addAllMessages(other.batches_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Batches parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Batches) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int rfwid_ ;
      /**
       * <code>int32 rfwid = 1;</code>
       * @return The rfwid.
       */
      @Override
      public int getRfwid() {
        return rfwid_;
      }
      /**
       * <code>int32 rfwid = 1;</code>
       * @param value The rfwid to set.
       * @return This builder for chaining.
       */
      public Builder setRfwid(int value) {
        
        rfwid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 rfwid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRfwid() {
        
        rfwid_ = 0;
        onChanged();
        return this;
      }

      private int lastID_ ;
      /**
       * <code>int32 lastID = 2;</code>
       * @return The lastID.
       */
      @Override
      public int getLastID() {
        return lastID_;
      }
      /**
       * <code>int32 lastID = 2;</code>
       * @param value The lastID to set.
       * @return This builder for chaining.
       */
      public Builder setLastID(int value) {
        
        lastID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 lastID = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastID() {
        
        lastID_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<Batch> batches_ =
        java.util.Collections.emptyList();
      private void ensureBatchesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          batches_ = new java.util.ArrayList<Batch>(batches_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Batch, Batch.Builder, BatchOrBuilder> batchesBuilder_;

      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public java.util.List<Batch> getBatchesList() {
        if (batchesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(batches_);
        } else {
          return batchesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public int getBatchesCount() {
        if (batchesBuilder_ == null) {
          return batches_.size();
        } else {
          return batchesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public Batch getBatches(int index) {
        if (batchesBuilder_ == null) {
          return batches_.get(index);
        } else {
          return batchesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public Builder setBatches(
          int index, Batch value) {
        if (batchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBatchesIsMutable();
          batches_.set(index, value);
          onChanged();
        } else {
          batchesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public Builder setBatches(
          int index, Batch.Builder builderForValue) {
        if (batchesBuilder_ == null) {
          ensureBatchesIsMutable();
          batches_.set(index, builderForValue.build());
          onChanged();
        } else {
          batchesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public Builder addBatches(Batch value) {
        if (batchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBatchesIsMutable();
          batches_.add(value);
          onChanged();
        } else {
          batchesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public Builder addBatches(
          int index, Batch value) {
        if (batchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBatchesIsMutable();
          batches_.add(index, value);
          onChanged();
        } else {
          batchesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public Builder addBatches(
          Batch.Builder builderForValue) {
        if (batchesBuilder_ == null) {
          ensureBatchesIsMutable();
          batches_.add(builderForValue.build());
          onChanged();
        } else {
          batchesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public Builder addBatches(
          int index, Batch.Builder builderForValue) {
        if (batchesBuilder_ == null) {
          ensureBatchesIsMutable();
          batches_.add(index, builderForValue.build());
          onChanged();
        } else {
          batchesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public Builder addAllBatches(
          Iterable<? extends Batch> values) {
        if (batchesBuilder_ == null) {
          ensureBatchesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, batches_);
          onChanged();
        } else {
          batchesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public Builder clearBatches() {
        if (batchesBuilder_ == null) {
          batches_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          batchesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public Builder removeBatches(int index) {
        if (batchesBuilder_ == null) {
          ensureBatchesIsMutable();
          batches_.remove(index);
          onChanged();
        } else {
          batchesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public Batch.Builder getBatchesBuilder(
          int index) {
        return getBatchesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public BatchOrBuilder getBatchesOrBuilder(
          int index) {
        if (batchesBuilder_ == null) {
          return batches_.get(index);  } else {
          return batchesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public java.util.List<? extends BatchOrBuilder>
           getBatchesOrBuilderList() {
        if (batchesBuilder_ != null) {
          return batchesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(batches_);
        }
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public Batch.Builder addBatchesBuilder() {
        return getBatchesFieldBuilder().addBuilder(
            Batch.getDefaultInstance());
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public Batch.Builder addBatchesBuilder(
          int index) {
        return getBatchesFieldBuilder().addBuilder(
            index, Batch.getDefaultInstance());
      }
      /**
       * <code>repeated .Batch batches = 3;</code>
       */
      public java.util.List<Batch.Builder>
           getBatchesBuilderList() {
        return getBatchesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Batch, Batch.Builder, BatchOrBuilder>
          getBatchesFieldBuilder() {
        if (batchesBuilder_ == null) {
          batchesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Batch, Batch.Builder, BatchOrBuilder>(
                  batches_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          batches_ = null;
        }
        return batchesBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Batches)
    }

    // @@protoc_insertion_point(class_scope:Batches)
    private static final Batches DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Batches();
    }

    public static Batches getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Batches>
        PARSER = new com.google.protobuf.AbstractParser<Batches>() {
      @Override
      public Batches parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Batches(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Batches> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Batches> getParserForType() {
      return PARSER;
    }

    @Override
    public Batches getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Metric_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Metric_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Batch_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Batch_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Batches_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Batches_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016response.proto\"$\n\006Metric\022\n\n\002id\030\001 \001(\005\022\016" +
      "\n\006metric\030\002 \001(\001\"!\n\005Batch\022\030\n\007metrics\030\001 \003(\013" +
      "2\007.Metric\"A\n\007Batches\022\r\n\005rfwid\030\001 \001(\005\022\016\n\006l" +
      "astID\030\002 \001(\005\022\027\n\007batches\030\003 \003(\0132\006.BatchB\nB\010" +
      "Responseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Metric_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Metric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Metric_descriptor,
        new String[] { "Id", "Metric", });
    internal_static_Batch_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Batch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Batch_descriptor,
        new String[] { "Metrics", });
    internal_static_Batches_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Batches_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Batches_descriptor,
        new String[] { "Rfwid", "LastID", "Batches", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
